[build]
  command = "sudo apt-get update && sudo apt-get install -y build-essential && bundle install && jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.3.4"

[[plugins]]
  package = "netlify-plugin-ruby-dependencies"